version: "3.7"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # TODO: need to have a way of checking to what named version is latest pointing to ATM.
        JENKINS_VERSION: 2.265
    container_name: jenkins-master-template
    environment:
      _JENKINS_URL: "http://localhost:${HOST_HTTP_PORT}"
      JAVA_OPTS: "-Dhudson.footerURL=http://localhost:${HOST_HTTP_PORT}"
    ports:
      - "${HOST_HTTP_PORT}:8080/tcp"
      - "${HOST_NODES_PORT}:50000/tcp"
    volumes:
      - "jenkins_home:/var/jenkins_home"
volumes: 
  jenkins_home:
