version: "3.7"
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-master-template
    ports:
      - "${HOST_HTTP_PORT}:8080/tcp"
      - "${HOST_NODES_PORT}:50000/tcp"
    volumes:
      - "jenkins_home:/var/jenkins_home"
volumes: 
  jenkins_home:
